service: lambda-weather-api

plugins:
  - serverless-offline
  - serverless-dotenv-plugin # With the plugin enabled, all variables in .env are automatically imported

provider:
  name: aws
  runtime: nodejs20.x

functions:
  current:
    handler: dist/main.current
    events:
      - http:
          method: GET
          path: /weather/{city}
  historical:
    handler: dist/main.historical
    events:
      - http:
          method: GET
          path: /weather/history/{city}
